service: plasmatic-technology-sample

frameworkVersion: ">=2.0.0"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-s3-local
  
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  environment:
    DYNAMODB: plasmatic-technology

functions:
  #### PET API ####
  pet-upload-file:
    handler: src/components/pet/pet-api.uploadFile
    events:
      - http:
          path: pets/{id}/uploadImage
          method: post
          cors: true


  pet-create:
    handler: src/components/pet/pet-api.create
    events:
      - http:
          path: pets
          method: post
          cors: true
  
  pet-update:
    handler: src/components/pet/pet-api.update
    events:
      - http:
          path: pets
          method: put
          cors: true

  pet-find-by-status:
    handler: src/components/pet/pet-api.findByStatus
    events:
      - http:
          path: pets
          method: get
          cors: true
  
  pet-find-by-id:
    handler: src/components/pet/pet-api.findById
    events:
      - http:
          path: pets/{id}
          method: get
          cors: true
  
  pet-delete-by-id:
    handler: src/components/pet/pet-api.deleteById
    events:
      - http:
          path: pets/{id}
          method: delete
          cors: true
  #### STORE API ####
  store-order-create:
    handler: src/components/store/store-api.create
    events:
      - http:
          path: store/order
          method: post
          cors: true

  store-inventory-find-all:
    handler: src/components/store/store-api.findAll
    events:
      - http:
          path: store/inventory
          method: get
          cors: true
  
  store-order-find-by-id:
    handler: src/components/store/store-api.findById
    events:
      - http:
          path: store/order/{id}
          method: get
          cors: true
  
  store-order-delete-by-id:
    handler: src/components/store/store-api.deleteById
    events:
      - http:
          path: store/order/{id}
          method: delete
          cors: true


custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'
